#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

for FILE in $(git diff --cached --name-only --diff-filter=ACMRTUXB -- '*.cpp' '*.c' '*.h' '*.hpp')
do    
    RESULT="$(python scripts/file_validator.py $FILE)"
    BAD_RESULT=""

    if [ "$RESULT" != "$BAD_RESULT" ]
    then
        echo " => Was got errors while commiting changes:"
        echo "$RESULT"
        echo " => Try to fix issues and commit again"
        exit 1
    fi

    clang-format -i -style=file:.clang-format $FILE
done