site:
  title: Utils
  start_page: utils::index.adoc

antora:
  extensions:
    - '@antora/collector-extension'

content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    page-pagination: true
    experimental: true

output:
  dir: ./html
